### ISSUE TITLE
How to know if my assembly is NGen'd?

### ISSUE THREAD

**Issue by amkherad** [getsentry/sentry-dotnet-platform-abstractions#13]
I looked in the source code but I didn't find anything about NGen'd assemblies.

**Comment by bruno-garcia** [comment]
This library is distributed through NuGet. Inside the libraries are DLLs which contain only IL. I don't know which machine this DLL will end up running. To my knowledge, it's not a common practice to NGen assemblies distributed by NuGet.

Could you describe your need in more details?
